### ISSUE TITLE
'getWMIObject()' returns just one object, not all like 'getRawWMIObjectOutput()'

### ISSUE THREAD

**Issue by kriegaex** [profesorfalken/WMI4Java#3]
If e.g. I want to list all active printers like this, I get a printable represantation of all printers:

            WMI4Java
                .get()
                .properties(Arrays.asList("Name", "WorkOffline"))
                .filters(Arrays.asList("$_.WorkOffline -eq 0"))
                .getRawWMIObjectOutput(WMIClass.WIN32_PRINTER)

But this fairly equivalent call yields only one object's properties (the last one's in my case):

            WMI4Java
                .get()
                .properties(Arrays.asList("Name", "WorkOffline"))
                .filters(Arrays.asList("$_.WorkOffline -eq 0"))
                .getWMIObject(WMIClass.WIN32_PRINTER)

To me this looks like a bug. I would rather expect a result of type `List<Map<String, String>>` instead of just some random `Map<String, String>`

**Comment by kriegaex** [comment]
So as I already said in the PR:

Now I can do something like this (using Java Streams API) ...
```java
package de.scrum_master.app;

import com.profesorfalken.wmi4java.WMI4Java;
import com.profesorfalken.wmi4java.WMIClass;

import java.util.Arrays;
import java.util.stream.Collectors;

public class Printer {
    public static void main(String[] args) {
        System.out.println(
            WMI4Java
                .get()
                .properties(Arrays.asList("Name", "WorkOffline"))
                .filters(Arrays.asList("$_.WorkOffline -eq 0"))
                .getWMIObject(WMIClass.WIN32_PRINTER)
                .stream()
                .map(properties -> properties.get("Name"))
                .sorted()
                .collect(Collectors.toList())
        );
    }
}
```

... which yields the following output on my machine:

```
[Fax, FinePrint, FreePDF, Microsoft Print to PDF, Microsoft XPS Document Writer, Send To OneNote 2016, WEB.DE Club SmartFax]
```

**Comment by kriegaex** [comment]
Without this pull request I have to parse the raw output myself and do something like this in order to achieve the same result:

```java
package de.scrum_master.app;

import com.profesorfalken.wmi4java.WMI4Java;
import com.profesorfalken.wmi4java.WMIClass;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class Printer {
    public static void main(String[] args) {
        String rawOutput = WMI4Java
            .get()
            .properties(Arrays.asList("Name", "WorkOffline"))
            .filters(Arrays.asList("$_.WorkOffline -eq 0"))
            .getRawWMIObjectOutput(WMIClass.WIN32_PRINTER);
        List<String> printers = Arrays.stream(rawOutput.split("(\r?\n)"))
            .filter(line -> line.startsWith("Name"))
            .map(line -> line.replaceFirst(".* : ", ""))
            .sorted()
            .collect(Collectors.toList());
        System.out.println(printers);
    }
}
```

**Comment by profesorfalken** [comment]
Hello, 

I see your point. However while it is a good solution for your need, the usage of the method is kind of weird when we only want to retrieve the properties of an object (ex: BIOS information).

What do you think of creating a new method _getWmiObjectList_ that returns a list, keeping the existing 'flat' one?

Best regards

**Comment by kriegaex** [comment]
I think that it is rather common that `Get-WMIObject` returns multiple elements (e.g. drivers, services, hard disks, printers, processes) and if it returns just one this is merely a special case, a one-element list (e.g. BIOS). So if a user is absolutely sure that she always gets just one element or wants to grab the first one even if there happen to be multiple ones, she can always call `.get(0)` upon the result list. I think this is easier than having additional API methods.

But hey, this is your project and if you do not like my PR you can always refactor it into something else.

**Update:** In any case, your code for the flat map is buggy because you iterate over all lines and create some kind of a union of properties across all returned objects with always the last found one winning. E.g. if for some reason the result would look like this

```
One   : foo
Two   : bar

One   : xxx
Three : yyy
```

your flattened result would be like

```
One   : xxx
Two   : bar
Three : yyy
```

**Comment by profesorfalken** [comment]
Ok. I think that you are right in the sense that we normally make the WMI queries to enumerate hardware. But I will like to keep the map/flat functionnality also so maybe I will do a new method any way to handle the 'flat' case. I guess I will accept you pr and refactor the code in order to create the new version (I will do it when I will have the time!).

In the case of the map, the inconsistency is indeed inevitable if the same keys are repeated. I could control the pre-existence of the key before updating it but even in that case that could finish in inconsistent content. Maybe I should abort the first time a duplicate occurs... I will think about it.

Thank you

**Comment by profesorfalken** [comment]
Done in 1.5 version.

Thanks
