### ISSUE TITLE
Parameter computerName is not used on WMIPowershell

### ISSUE THREAD

**Issue by guilhermeoliveiradecarvalho** [profesorfalken/WMI4Java#6]
The parameter computerName on the `WMIPowershell` class is currently not used. The result is that even when specifying a computer name when using the Powershell engine, all WMI queries will be made against the local computer's WMI database.

A possible fix is to add the following lines to the `listClasses`, `listProperties`, `listObject` and `queryObject` methods on the `WMIPowershell` class, before executing the query:

    if (!computerName.isEmpty()) {
        command += "-ComputerName" + computerName;
    }

**Comment by profesorfalken** [comment]
Hello, 

After a quick check, I see you are totally right.
I will try to find the time this week to make the fix.

Thanks.

**Comment by profesorfalken** [comment]
Hello again, 

It should work with the new 1.5 version.

Could you check it?

Regards

**Comment by guilhermeoliveiradecarvalho** [comment]
Error calling WMI4Java
    com.profesorfalken.wmi4java.WMIException: WMI operation finished in error: Get-WMIObject : Invalid Namespace "root/CIMv2-ComputerName"

Looks like it's missing a space. Lines 128-130:

    if (!"*".equals(namespace)) {
        command += NAMESPACE_PARAM + namespace;
    }

Correct code would have `command += NAMESPACE_PARAM + namespace + " ";` inside your `if` block.

**Comment by profesorfalken** [comment]
Hello, 

You are right again. 
I have just pushed the fix and the 1.5.1 version should be up on maven central in some minutes.

Thanks

**Comment by guilhermeoliveiradecarvalho** [comment]
Looks like it's working now! I'll test more of it later on remote networked computers and different setups, but it's doing its' job so far.
EDIT: Also, 1.5.1 isn't up in maven yet, had to compile it from `master`.

**Comment by guilhermeoliveiradecarvalho** [comment]
The issue has been resolved, it's working as it should with the Powershell engine.
Maven repository hasn't been updated though, going to the 1.5.1 page gives a 404.
